app/config/routes.rb
# Copyright (C) 2025 Frank Mayer, Enes Korkmaz, Jascha Sonntag, Andreas Rothaler, Eray Akyazililar, Jan Magister
#
# This file is part of Elink.
#
# Elink is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Elink is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Elink. If not, see <http://www.gnu.org/licenses/>.

Rails.application.routes.draw do
  resources :projects do
    member do
      # Document Removal
      patch "remove_document"

      # Partner Management
      get "add_partner", to: "projects#add_partner"
      post "save_partner"
      get "edit_partner", to: "projects#edit_partner"
      patch "save_partner", to: "projects#save_partner"
      delete "delete_partner", to: "projects#delete_partner"
      get "remove_partner_document", to: "projects#remove_partner_document"

      # Accommodation Management
      get "add_accommodation", to: "projects#add_accommodation"
      post "save_accommodation"
      get "edit_accommodation", to: "projects#edit_accommodation"
      patch "save_accommodation", to: "projects#save_accommodation"
      delete "delete_accommodation", to: "projects#delete_accommodation"
      get "remove_accommodation_document", to: "projects#remove_accommodation_document"

      # Catering Management
      get "add_catering", to: "projects#add_catering"
      post "save_catering"
      get "edit_catering", to: "projects#edit_catering"
      patch "save_catering", to: "projects#save_catering"
      delete "delete_catering", to: "projects#delete_catering"
      get "remove_catering_document", to: "projects#remove_catering_document"

      # Transport Management
      get "add_transport", to: "projects#add_transport"
      post "save_transport"
      get "edit_transport", to: "projects#edit_transport"
      patch "save_transport", to: "projects#save_transport"
      delete "delete_transport", to: "projects#delete_transport"
      get "remove_transport_document", to: "projects#remove_transport_document"

      post "add_experts", to: "projects#add_experts"
      delete "unassign_expert/:expert_id", to: "projects#unassign_expert", as: :unassign_expert
    end
  end

  # Registration
  get "register/:token",
    to: "registrations#new",
    constraints: { token: %r{[^/]+} },
    as: "register"

  post "register/:token",
    to: "registrations#create",
    constraints: { token: %r{[^/]+} }

  resources :project_types
  resources :key_topics
  resources :categories

  resources :experts
  root "home#overview"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "home/overview", to: "home#overview", as: "home_overview"
  # Routes for login, logout, and sessions management
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"

  get "sessions/destroy"
  delete "logout", to: "sessions#destroy"

  # Additional routes
  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Calendar routes
  get "calendar/month", to: "calendar#month"
end

app/app/controllers/home_controller.rb
# Copyright (C) 2025 Frank Mayer, Enes Korkmaz, Jascha Sonntag, Andreas Rothaler, Eray Akyazililar, Jan Magister
#
# This file is part of Elink.
#
# Elink is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Elink is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Elink. If not, see <http://www.gnu.org/licenses/>.

class HomeController < ApplicationController
  before_action :authorize_user

  def overview
    add_breadcrumb I18n.t("nav_bar.homepage")
    @recently_invoked = Project.where("updated_at > ?", 7.days.ago).order(updated_at: :desc).limit(10)
    @recently_added = Project.order(created_at: :desc).limit(10)
    @in_planing = Project.where(project_status: :planning).order(project_date_from: :asc)
    @recently_finished = Project.where(project_status: :completed)
                             .where("updated_at >= ? OR created_at >= ?", 1.week.ago, 1.week.ago)
                             .order(updated_at: :desc)
                             .limit(10)

    @recently_updated = Expert.where("updated_at >= ?", 1.week.ago).order(updated_at: :desc).limit(10)
    @recently_registered = Expert.where("created_at >= ?", 1.week.ago).order(created_at: :desc).limit(10)
  end

  private

  def authorize_user
    unless current_user&.role.in?(%w[intern employee])
      flash[:alert] = I18n.t("flash.access_denied2")
      redirect_to expert_path(current_user.expert)
    end
  end
end

app/app/helpers/home_helper.rb
# Copyright (C) 2025 Frank Mayer, Enes Korkmaz, Jascha Sonntag, Andreas Rothaler, Eray Akyazililar, Jan Magister
#
# This file is part of Elink.
#
# Elink is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Elink is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Elink. If not, see <http://www.gnu.org/licenses/>.

module HomeHelper
end

app/app/views/home/_footer.html.erb
<%
# Copyright (C) 2025 Frank Mayer, Enes Korkmaz, Jascha Sonntag, Andreas Rothaler, Eray Akyazililar, Jan Magister
#
# This file is part of Elink.
#
# Elink is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Elink is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Elink. If not, see <http://www.gnu.org/licenses/>.
%>


<footer id="footer" class="text-xs text-center bg-white shadow">
  <p>AGPL 2025 ƎLink</p>
</footer>

<script defer>
  const content = document.getElementById('content');
  const footer = document.getElementById('footer');

  // Wenn der Content kleiner als das Fenster ist, fixiere den Footer unten.
  if (document.body.scrollHeight <= window.innerHeight) {
    footer.style.position = "fixed";
    footer.style.bottom = "0";
    footer.style.width = "100%";
  } else {
    // Sonst lasse den Footer nach Scroll sichtbar werden.
    footer.style.position = "relative";
  }
</script>

app/app/views/home/_header.html.erb
<%
# Copyright (C) 2025 Frank Mayer, Enes Korkmaz, Jascha Sonntag, Andreas Rothaler, Eray Akyazililar, Jan Magister
#
# This file is part of Elink.
#
# Elink is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Elink is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Elink. If not, see <http://www.gnu.org/licenses/>.
%>

<header class="flex items-center p-2 bg-white shadow">
  <% if current_user %>
    <% if current_user.role == "expert" %>
      <h1 class="text-xl text-red-700">ƎLink</h1>
    <% else %>
      <h1><%= link_to "ƎLink", root_path, class: "text-xl text-red-700" %></h1>
    <% end %>

    <ol class="mr-auto breadcrumbs">
      <%= render_breadcrumbs tag: :li, separator: "" %>
    </ol>

    <!-- Main Navigation -->
    <nav class="flex items-center space-x-3">
      <% if current_user.role == "employee" || current_user.role == "intern" %>
        <%= link_to root_path, class: "flex hover:bg-red-700 hover:text-white rounded-lg px-3 py-2" do %>
          <%= image_tag("svg/home.svg", class: "mr-2") %>
          <%= t("nav_bar.homepage") %>
        <% end %>
        <%= link_to experts_path, class: "flex hover:bg-red-700 hover:text-white rounded-lg px-3 py-2" do %>
          <%= image_tag("svg/person.svg", class: "mr-2") %>
          <%= t("nav_bar.experts") %>
        <% end %>
        <%= link_to projects_path, class: "flex hover:bg-red-700 hover:text-white rounded-lg px-3 py-2" do %>
          <%= image_tag("svg/folder.svg", class: "mr-2") %>
          <%= t("nav_bar.projects") %>
        <% end %>
      <% end %>

      <!-- Dropdown for Other Options -->
      <div class="relative">
        <button id="menu-toggle" class="flex py-2 px-3 rounded-lg hover:bg-red-700">
          <%= image_tag("svg/menu-bar.svg") %>
        </button>

        <!-- Dropdown Menu -->
        <div id="menu" class="hidden absolute right-0 z-50 w-48 bg-white rounded-lg shadow-lg top-15">
          <% if current_user.role == "employee" %>
            <%= link_to new_category_path, class: "flex hover:bg-red-700 hover:text-white rounded-lg px-3 py-2" do %>
              <%= image_tag("svg/grad-cap-black.svg", class: "mr-2") %>
              <%= t("nav_bar.categories") %>
            <% end %>
            <%= link_to calendar_month_path, class: "flex items-center hover:bg-red-700 hover:text-white rounded-lg px-3 py-2" do %>
              <%= image_tag("svg/calendar-blank.svg", class: "mr-2") %>
              <%= t("nav_bar.calendar") %>
            <% end %>
          <% end %>
          <%= link_to login_path, class: "flex items-center hover:bg-red-700 hover:text-white rounded-lg px-3 py-2" do %>
            <%= image_tag("svg/log_out.svg", class: "mr-2") %>
            <%= t("nav_bar.logout") %>
          <% end %>
        </div>
      </div>
    </nav>
    <script>
      document.addEventListener("DOMContentLoaded", () => {
         const menuToggle = document.getElementById("menu-toggle");
         const menu = document.getElementById("menu");

         menuToggle.addEventListener("click", () => {
           menu.classList.toggle("hidden");
         });

         document.addEventListener("click", (event) => {
           if (!menu.contains(event.target) && !menuToggle.contains(event.target)) {
             menu.classList.add("hidden");
           }
         });
       });
    </script>
  <% else %>
    <h1 class="text-xl text-red-700">ƎLink</h1>
  <% end %>
</header>

app/app/views/home/overview.html.erb
<%
# Copyright (C) 2025 Frank Mayer, Enes Korkmaz, Jascha Sonntag, Andreas Rothaler, Eray Akyazililar, Jan Magister
#
# This file is part of Elink.
#
# Elink is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Elink is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Elink. If not, see <http://www.gnu.org/licenses/>.
%>

<div class="container">
  <!-- Sidebar -->
  <% if current_user.role == "employee" %>
    <div class="sidebar">
      <h2 class="mt-0.5 heading"><%= t("actions.title") %></h2>
      <div class="actions-container">
        <a href="/experts/new" class="relative btn">
          <%= image_tag("svg/new.svg", class: "absolute left-4") %><%= t("homepage.create_new_expert") %>
        </a>
        <a href="/projects/new" class="relative btn">
          <%= image_tag("svg/new.svg", class: "absolute left-4") %><%= t("homepage.create_new_project") %>
        </a>
        <button
          class="relative btn"
          data-link="<%= register_url(User.generate_registration_token) %>"
          onclick="navigator.clipboard.writeText(this.dataset.link).then(()=>{this.innerHTML = this.innerHTML.substring(0, this.innerHTML.length - 1) + '✓'}).catch((err)=>{this.innerHTML = this.innerHTML.substring(0, this.innerHTML.length - 1) + '✗'; alert(err)})"
        >
          <%= image_tag("svg/copy.svg", class: "absolute left-4 h-4") %><%= t("homepage.copy_invite_link") + " " %>
        </button>
      </div>
    </div>
  <% end %>
  <div class="w-full h-full md:w-auto flex-[3]">
    <div class="p-5 mb-3 bg-white rounded-lg border border-gray-300 shadow-sm">
      <div>
        <h2 class="heading"><%= t("homepage.projekt_overview") %></h2>
        <div class="container-row">
          <div class="container-second">
            <h3 class="heading-sub"><%= t("homepage.recently_updated") %></h3>
            <div class="overflow-y-auto max-h-40">
              <table class="min-w-full border-collapse table-auto">
                <tbody class="bg-gray-100">
                  <% @recently_invoked.each do |project| %>
                    <tr class="border-b hover:bg-red-200">
                      <td class="py-2 px-4">
                        <%= link_to project_path(project), class: "block py-2 px-4 w-full text-neutral-700  hover:underline" do %>
                          <%= project.project_name %>
                        <% end %>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        <div class="container-second">
          <h3 class="heading-sub"><%= t("homepage.recently_added") %></h3>
          <div class="overflow-y-auto max-h-40">
            <table class="min-w-full border-collapse table-auto">
              <tbody class="bg-gray-100">
                <% @recently_added.each do |project| %>
                  <tr class="border-b hover:bg-red-200">
                    <td class="py-2 px-4">
                      <%= link_to project_path(project), class: "block py-2 px-4 w-full text-neutral-700  hover:underline" do %>
                        <%= project.project_name %>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
       <div class="container-second">
          <h3 class="heading-sub"><%= t("homepage.in_planing") %></h3>
          <div class="overflow-y-auto max-h-40">
            <table class="min-w-full border-collapse table-auto">
              <tbody class="bg-gray-100">
                <% @in_planing.each do |project| %>
                  <tr class="border-b hover:bg-red-200">
                    <td class="py-2 px-4">
                      <%= link_to project_path(project), class: "block py-2 px-4 w-full text-neutral-700 hover:underline" do %>
                        <%= project.project_name %>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
        <div class="container-second">
          <h3 class="heading-sub"><%= t("homepage.recently_finished") %></h3>
          <div class="overflow-y-auto max-h-40">
            <table class="min-w-full border-collapse table-auto">
              <tbody class="bg-gray-100">
                <% @recently_finished.each do |project| %>
                  <tr class="border-b hover:bg-red-200">
                    <td class="py-2 px-4">
                      <%= link_to project_path(project), class: "block py-2 px-4 w-full text-neutral-700  hover:underline" do %>
                        <%= project.project_name %>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

    <div class="p-5 bg-white rounded-lg border border-gray-300 shadow-sm">
  <div>
    <h2 class="heading"><%= t("homepage.experts_overview") %></h2>
    <div class="container-row">
      <div class="container-second">
        <h3 class="heading-sub"><%= t("homepage.recently_updated") %></h3>
        <div class="overflow-y-auto max-h-40">
          <table class="min-w-full border-collapse table-auto">
            <tbody class="bg-gray-100">
              <% @recently_updated.each do |expert| %>
                <tr class="border-b hover:bg-red-200">
                  <td class="py-2 px-4">
                    <%= link_to expert_path(expert), class: "block py-2 px-4 w-full text-neutral-700  hover:underline" do %>
                      <%= truncate("#{expert.title} #{expert.last_name}, #{expert.first_name} ", length: 20) %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>

      <div class="container-second">
        <h3 class="heading-sub"><%= t("homepage.recently_registered") %></h3>
        <div class="overflow-y-auto max-h-40">
          <table class="min-w-full border-collapse table-auto">
            <tbody class="bg-gray-100">
              <% @recently_registered.each do |expert| %>
                <tr class="border-b hover:bg-red-200">
                  <td class="py-2 px-4">
                    <%= link_to expert_path(expert), class: "block py-2 px-4 w-full text-neutral-700  hover:underline" do %>
                      <%= truncate("#{expert.title} #{expert.last_name}, #{expert.first_name} ", length: 20) %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>