app/config/routes.rb
# Copyright (C) 2025 Frank Mayer, Enes Korkmaz, Jascha Sonntag, Andreas Rothaler, Eray Akyazililar, Jan Magister
#
# This file is part of Elink.
#
# Elink is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Elink is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Elink. If not, see <http://www.gnu.org/licenses/>.

Rails.application.routes.draw do
  resources :projects do
    member do
      # Document Removal
      patch "remove_document"

      # Partner Management
      get "add_partner", to: "projects#add_partner"
      post "save_partner"
      get "edit_partner", to: "projects#edit_partner"
      patch "save_partner", to: "projects#save_partner"
      delete "delete_partner", to: "projects#delete_partner"
      get "remove_partner_document", to: "projects#remove_partner_document"

      # Accommodation Management
      get "add_accommodation", to: "projects#add_accommodation"
      post "save_accommodation"
      get "edit_accommodation", to: "projects#edit_accommodation"
      patch "save_accommodation", to: "projects#save_accommodation"
      delete "delete_accommodation", to: "projects#delete_accommodation"
      get "remove_accommodation_document", to: "projects#remove_accommodation_document"

      # Catering Management
      get "add_catering", to: "projects#add_catering"
      post "save_catering"
      get "edit_catering", to: "projects#edit_catering"
      patch "save_catering", to: "projects#save_catering"
      delete "delete_catering", to: "projects#delete_catering"
      get "remove_catering_document", to: "projects#remove_catering_document"

      # Transport Management
      get "add_transport", to: "projects#add_transport"
      post "save_transport"
      get "edit_transport", to: "projects#edit_transport"
      patch "save_transport", to: "projects#save_transport"
      delete "delete_transport", to: "projects#delete_transport"
      get "remove_transport_document", to: "projects#remove_transport_document"

      post "add_experts", to: "projects#add_experts"
      delete "unassign_expert/:expert_id", to: "projects#unassign_expert", as: :unassign_expert
    end
  end

  # Registration
  get "register/:token",
    to: "registrations#new",
    constraints: { token: %r{[^/]+} },
    as: "register"

  post "register/:token",
    to: "registrations#create",
    constraints: { token: %r{[^/]+} }

  resources :project_types
  resources :key_topics
  resources :categories

  resources :experts
  root "home#overview"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "home/overview", to: "home#overview", as: "home_overview"
  # Routes for login, logout, and sessions management
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"

  get "sessions/destroy"
  delete "logout", to: "sessions#destroy"

  # Additional routes
  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Calendar routes
  get "calendar/month", to: "calendar#month"
end

app/app/controllers/experts_controller.rb
# Copyright (C) 2025 Frank Mayer, Enes Korkmaz, Jascha Sonntag, Andreas Rothaler, Eray Akyazililar, Jan Magister
#
# This file is part of Elink.
#
# Elink is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Elink is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Elink. If not, see <http://www.gnu.org/licenses/>.

class ExpertsController < ApplicationController
  before_action :set_expert, only: %i[ show edit update destroy ]

  add_breadcrumb I18n.t("nav_bar.experts"), :experts_path, unless: -> { current_user.role == "expert" }

  # GET /experts or /experts.json
  def index
    if !authorize_user
      return
    end
    @experts = Expert.all

    @recently_updated = Expert.where("updated_at >= ?", 1.week.ago).order(updated_at: :desc).limit(10)
    @recently_registered = Expert.where("created_at >= ?", 1.week.ago).order(created_at: :desc).limit(10)
  end

  def authorize_user
    unless current_user&.role.in?(%w[intern employee])
      flash[:alert] = I18n.t("flash.access_denied2")
      redirect_to expert_path(current_user.expert)
      return false
    end
    true
  end

  def authorize_user_allow_empty_expert
    return true if current_user&.role.in?(%w[intern employee])

    return true if current_user&.role == "expert" && current_user.expert.nil?

    flash[:alert] = I18n.t("flash.access_denied2")
    redirect_to expert_path(current_user.expert)
    false
  end

  def authorize_user_allow_own_expert
    return true if current_user&.role.in?(%w[intern employee])

    return true if current_user&.role == "expert" && current_user.expert.id == @expert.id

    flash[:alert] = I18n.t("flash.access_denied2")
    redirect_to expert_path(current_user.expert)
    false
  end

  # GET /experts/1 or /experts/1.json
  def show
    add_breadcrumb "#{@expert.title} #{@expert.last_name}, #{@expert.first_name}", :expert_path
    authorize_user_allow_own_expert
  end

  # GET /experts/new
  def new
    if !authorize_user_allow_empty_expert
      return
    end
    @expert = Expert.new
    if current_user&.role == "expert"
      @expert.email = current_user.username
    end
    add_breadcrumb I18n.t("homepage.create_new_expert")
  end

  # GET /experts/1/edit
  def edit
    authorize_user_allow_own_expert
    add_breadcrumb "#{@expert.title} #{@expert.last_name}, #{@expert.first_name}", :expert_path
    add_breadcrumb I18n.t("actions.edit")
  end

  # POST /experts or /experts.json
  def create
    if !authorize_user_allow_empty_expert
      return
    end
    @expert = Expert.new(expert_params)
    if current_user.role == "expert"
      @expert[:user_id] = current_user.id
    end

    respond_to do |format|
      if @expert.save
        format.html { redirect_to @expert, notice: I18n.t("flash.expert_created") }
        format.json { render :show, status: :created, location: @expert }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @expert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /experts/1 or /experts/1.json
  def update
    if !authorize_user_allow_own_expert
      return
    end
    @del_doc = false
    @duplicate_certificates = false
    @update_params = expert_params

    # Remove document removal flags from params before checking for parameter changes
    filtered_params = @update_params.except(:remove_profile_picture, :remove_resume, :remove_certificates)

    if document_removal_requested
      @del_doc = true
    end

    @duplicate_certificates = true if duplicate_files_detected?

    if check_for_param_changes(filtered_params)
      respond_to do |format|
        if @del_doc
          if @expert.update(filtered_params)
            handleDuplicateCertificates() if @duplicate_certificates
            remove_document(filtered_params)
            flash[:notices] = [ flash[:notices], t("flash.expert_updated") ].compact.join(" ")
            format.html { render :edit, notice: flash[:notices] }
            format.json { render :show, status: :ok, location: @expert }
          else
            flash[:alerts] = [ flash[:alert], t("notices.expert_update_failed") ].compact.join(" ")
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @expert.errors, status: :unprocessable_entity }
          end
        else
          if @expert.update(filtered_params)
            handleDuplicateCertificates() if @duplicate_certificates
            format.html { redirect_to @expert, notice: t("flash.expert_updated") }
            format.json { render :show, status: :ok, location: @expert }
          else
            flash[:alert] = t("notices.expert_update_failed")
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @expert.errors, status: :unprocessable_entity }
          end
        end
      end
    else
      if @del_doc
        # If only deleting doc(s)
        remove_document(filtered_params)
      end
    end
  end

  # DELETE /experts/1 or /experts/1.json
  def destroy
    if !authorize_user
      return
    end
    @expert.destroy!
    # handle redirect when user role expert destroys
    respond_to do |format|
      format.html { redirect_to experts_path, status: :see_other, notice: I18n.t("flash.expert_destroyed") }
      format.json { head :no_content }
    end
  end

  def remove_document(filtered_params)
    %i[profile_picture resume].each do |document_name|
      if params[:expert]["remove_#{document_name}"] == "true"
        document = @expert.send(document_name)
        if document.attached?
          document.purge_later
          message = t("notices.delete_success", document: t("activerecord.attributes.expert.documents.#{document_name}"))
          # Append message if there are other changes, otherwise just show the success message
          flash[:notices] = if filtered_params.present?
                            [ flash[:notice], message ]
          else
                           message
          end
        else
          message = t("notices.delete_failed", document: t("activerecord.attributes.expert.documents.#{document_name}"))
          # Append message if there are other changes, otherwise just show the failure message
          flash[:alerts] = if filtered_params.present?
                          [ flash[:alert], message ]
          else
                          message
          end
        end
      end
    end
  end

  # Method to handle duplicate certificates deletion and attaching the new ones
  def handleDuplicateCertificates
    if params[:expert][:certificates].present?
      params[:expert][:certificates].each do |new_file|
        next unless new_file.is_a?(ActionDispatch::Http::UploadedFile)

        # Find existing files with the same name and remove them
        existing_files = @expert.certificates.select do |certificate|
          certificate.filename.to_s == new_file.original_filename
        end

        # Detach old files
        existing_files.each(&:purge)

        # Attach the new file after purging the old one
        @expert.certificates.attach(new_file)
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expert
      @expert = Expert.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def expert_params
      params.require(:expert).permit(:salutation, :title, :first_name, :last_name,
                                    :nationality, :phone_number, :email,
                                    :current_location, :language_id,
                                    :hourly_rate, :daily_rate,
                                    :travel_willingness_online, :travel_willingness_germany,
                                    :travel_willingness_china, :travel_willingness_text,
                                    :spontaneous, :has_china_reference, :china_reference,
                                    :extra_skills, :has_institution, :institution_name,
                                    :cooperation_options, :free_text, :profile_picture,
                                    :resume, certificates: [], language_ids: [], category_ids: [])
    end

    def check_for_param_changes(filtered_params)
      filtered_params.to_h.any? do |key, value|
        # Check if the value in the project is different
        @expert.read_attribute(key.to_s) != value
      end
    end

    def document_removal_requested
      %w[profile_picture resume].any? do |doc_name|
        params[:expert]["remove_#{doc_name}"] == "true"
    end

    def duplicate_files_detected?
      return false unless params[:expert][:certificates].present?

      params[:expert][:certificates].each do |new_file|
        next unless new_file.is_a?(ActionDispatch::Http::UploadedFile)

        # Check for existing certificates with the same name
        existing_certificates = @expert.certificates.select do |certificate|
          certificate.filename.to_s == new_file.original_filename
        end

        # Return true if there are any existing certificates with the same filename
        return existing_certificates.any?
      end

      false # Ensure that false is returned if no duplicate is found
    end
  end
end

app/app/helpers/expert_helper.rb
# Copyright (C) 2025 Frank Mayer, Enes Korkmaz, Jascha Sonntag, Andreas Rothaler, Eray Akyazililar, Jan Magister
#
# This file is part of Elink.
#
# Elink is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Elink is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Elink. If not, see <http://www.gnu.org/licenses/>.

module ExpertHelper
end

app/app/helpers/experts_helper.rb
# Copyright (C) 2025 Frank Mayer, Enes Korkmaz, Jascha Sonntag, Andreas Rothaler, Eray Akyazililar, Jan Magister
#
# This file is part of Elink.
#
# Elink is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Elink is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Elink. If not, see <http://www.gnu.org/licenses/>.

module ExpertsHelper
end

app/app/views/experts/edit.html.erb
<%
# Copyright (C) 2025 Frank Mayer, Enes Korkmaz, Jascha Sonntag, Andreas Rothaler, Eray Akyazililar, Jan Magister
#
# This file is part of Elink.
#
# Elink is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Elink is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Elink. If not, see <http://www.gnu.org/licenses/>.
%>

<div class="container">
  <!-- Sidebar -->
  <div class="sidebar">
    <h2 class="heading"><%= t("actions.title") %></h2>
    <% if current_user.role == "employee" %>
       <%= link_to expert_path, 
            class: "btn relative", 
            id: "expert_edit_cancel_editing_button", 
            onclick: "return confirm('#{I18n.t("actions.expert.confirm_cancel.editing")}')" do %>
        <%= image_tag("svg/back.svg", class: "absolute left-4") %>
        <%= t("actions.back") %>
      <% end %>
      <a href="#" class="relative btn" id="expert_edit_save_button"
         onclick="document.getElementById('create_expert_form').submit(); return false;">
        <%= image_tag("svg/save.svg", class: "absolute left-4") %>
        <%= t("actions.save") %>
      </a>
    <% elsif current_user.role == "expert" %>
      <%= link_to @expert, 
            class: "btn relative", 
            id: "expert_edit_cancel_editing_button", 
            onclick: "return confirm('#{I18n.t("actions.expert.confirm_cancel.editing")}')" do %>
        <%= image_tag("svg/back.svg", class: "absolute left-4") %>
        <%= t("actions.back") %>
      <% end %>
      <a href="#" class="relative btn" id="expert_edit_save_button"
         onclick="document.getElementById('create_expert_form').submit(); return false;">
        <%= image_tag("svg/save.svg", class: "absolute left-4") %>
        <%= t("actions.save") %>
      </a>
    <% end %>
  </div>

  <div class="w-full md:w-auto flex-[3]">
    <div class="flex-[40%] w-full">
      <%= render "form", expert: @expert %>
    </div>
  </div>
</div>

app/app/views/experts/index.html.erb
<%
# Copyright (C) 2025 Frank Mayer, Enes Korkmaz, Jascha Sonntag, Andreas Rothaler, Eray Akyazililar, Jan Magister
#
# This file is part of Elink.
#
# Elink is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Elink is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Elink. If not, see <http://www.gnu.org/licenses/>.
%>

<%= javascript_include_tag "filter_table", defer: true %>
<%= javascript_include_tag "sort", async: true %>
<%= javascript_include_tag "add_to_project", async: true %>

<div class="container">
    <div class="sidebar">
        <% if current_user.role == "employee" %>
            <!-- Actions section first -->
            <h3 class="heading"><%= t("actions.title") %></h3>
            <!-- Create button -->
            <%= link_to new_expert_path, class: "btn relative create-btn" do %>
                <%= image_tag("svg/new.svg", class: "absolute left-4") %>
                <%= t("actions.create") %>
            <% end %>
        <% end %>

        <!-- Add to Project button, hidden by default -->
        <button class="hidden btn add-btn"><%= t("actions.add_to_project") %></button>

        <!-- Now comes the Filter section -->
        <h2 class="heading" style="mt-4">Filter</h2>
        <div class="filter_table" data-for="experts_table"></div>
    </div>



    <div class="md:w-1 container-second">
        <div class="overflow-hidden max-w-full">
            <div class="overflow-x-auto overflow-y-auto shadow-md sm:rounded-lg max-h-[88vh]" style="width: 100%">
                <table class="w-full text-left table-auto" id="experts_table">
                    <thead>
                        <tr>
                            <th class="text-center cursor-pointer hover:text-red-700" onclick="orderBy(this, Number.parseInt)">#</th>
                            <th class="cursor-pointer hover:text-red-700" onclick="orderBy(this)"><%= t("index.name_contact") %></th>
                            <th class="cursor-pointer hover:text-red-700" onclick="orderBy(this)"><%= t("index.categories") %></th>
                            <th class="text-right cursor-pointer hover:text-red-700" onclick="orderBy(this, Number.parseInt)" data-filter-type="number"><%= t("activerecord.attributes.expert.hourly_rate") %></th>
                            <th class="text-right cursor-pointer hover:text-red-700" onclick="orderBy(this, Number.parseInt)" data-filter-type="number"><%= t("activerecord.attributes.expert.daily_rate") %></th>
                            <!-- This is for the icon column with no text -->
                            <th class=""></th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @experts.each_with_index do |expert, index| %>

                            <tr class="border-b border-gray-400" data-expert-id="<%= expert.id %>" onclick="window.location='<%= expert_path(expert) %>'">

                                <td class="text-center"><%= index + 1 %></td>

                                <td>
                                    <div>
                                        <!-- no_value gets filterd, because the String value is not nothing -->
                                        <% unless expert.salutation == "mx" %>
                                        <%= "#{t("activerecord.attributes.expert.salutations.#{expert.salutation}")} " %>
                                        <% end %>
                                        <%= truncate("#{expert.title} #{expert.last_name}, #{expert.first_name} ", length: 24) %>
                                    </div>
                                    <div><%= truncate(expert.email, length: 25) %></div>
                                </td>

                                <!-- Up to 5 categories can easily be rendered everything above will need adjustments in the view -->
                                <td >
                                    <% categories = expert.categories.map(&:name) %>

                                    <% if categories.length == 1 %>
                                        <%= categories.first %>
                                    <% elsif categories.length == 2 %>
                                        <%= categories.join(" & ") %>
                                    <% else %>
                                        <!-- [0..-2] - This will get all items until the second last -->
                                        <%= categories[0..-2].join(", ") %> <br>& <%= categories.last %> <br>
                                    <% end %>
                                </td>



                                <td class="text-right">
                                    <%= number_to_currency(expert.hourly_rate, unit: t("currency.hourly")) %>
                                </td>
                                <td class="text-right">
                                  <%= number_to_currency(expert.daily_rate, unit: t("currency.daily")) %>
                                </td>

                                <td class="item-center"><%= image_tag("svg/chevron-right.svg", class: "w-4 aspect-square block max-w-none") %></td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

app/app/views/experts/new.html.erb
<%
# Copyright (C) 2025 Frank Mayer, Enes Korkmaz, Jascha Sonntag, Andreas Rothaler, Eray Akyazililar, Jan Magister
#
# This file is part of Elink.
#
# Elink is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Elink is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Elink. If not, see <http://www.gnu.org/licenses/>.
%>

<div class="container">
  <!-- Sidebar -->
  <div class="sidebar">
    <h2 class="heading"><%= t("actions.title") %></h2>
    <% if current_user.role == "employee" %>
      <%= link_to experts_path,
            class: "btn relative",
            id: "expert_new_cancel_button",
            onclick: "return confirm('#{I18n.t("actions.expert.confirm_cancel.creating")}')" do %>
        <%= image_tag("svg/cancel.svg", class: "absolute left-4") %>
        <%= t("actions.cancel") %>
      <% end %>
    <% end %>
    <% if current_user.role == "employee" || current_user.role == "expert" %>
      <a href="#" class="relative btn" id="expert_new_create_button"
         onclick="document.getElementById('create_expert_form').submit(); return false;">
        <%= image_tag("svg/new.svg", class: "absolute left-4") %>
        <%= t("actions.create") %>
      </a>
    <% end %>
  </div>
  <div class="w-full md:w-auto flex-[3]">
    <div class="flex-[40%] w-full">
      <%= render "form", expert: @expert %>
    </div>
  </div>
</div>

app/app/views/experts/show.html.erb
<%
# Copyright (C) 2025 Frank Mayer, Enes Korkmaz, Jascha Sonntag, Andreas Rothaler, Eray Akyazililar, Jan Magister
#
# This file is part of Elink.
#
# Elink is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Elink is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Elink. If not, see <http://www.gnu.org/licenses/>.
%>

<%= render @expert %>