app/config/routes.rb
# Copyright (C) 2025 Frank Mayer, Enes Korkmaz, Jascha Sonntag, Andreas Rothaler, Eray Akyazililar, Jan Magister
#
# This file is part of Elink.
#
# Elink is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Elink is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Elink. If not, see <http://www.gnu.org/licenses/>.

Rails.application.routes.draw do
  resources :projects do
    member do
      # Document Removal
      patch "remove_document"

      # Partner Management
      get "add_partner", to: "projects#add_partner"
      post "save_partner"
      get "edit_partner", to: "projects#edit_partner"
      patch "save_partner", to: "projects#save_partner"
      delete "delete_partner", to: "projects#delete_partner"
      get "remove_partner_document", to: "projects#remove_partner_document"

      # Accommodation Management
      get "add_accommodation", to: "projects#add_accommodation"
      post "save_accommodation"
      get "edit_accommodation", to: "projects#edit_accommodation"
      patch "save_accommodation", to: "projects#save_accommodation"
      delete "delete_accommodation", to: "projects#delete_accommodation"
      get "remove_accommodation_document", to: "projects#remove_accommodation_document"

      # Catering Management
      get "add_catering", to: "projects#add_catering"
      post "save_catering"
      get "edit_catering", to: "projects#edit_catering"
      patch "save_catering", to: "projects#save_catering"
      delete "delete_catering", to: "projects#delete_catering"
      get "remove_catering_document", to: "projects#remove_catering_document"

      # Transport Management
      get "add_transport", to: "projects#add_transport"
      post "save_transport"
      get "edit_transport", to: "projects#edit_transport"
      patch "save_transport", to: "projects#save_transport"
      delete "delete_transport", to: "projects#delete_transport"
      get "remove_transport_document", to: "projects#remove_transport_document"

      post "add_experts", to: "projects#add_experts"
      delete "unassign_expert/:expert_id", to: "projects#unassign_expert", as: :unassign_expert
    end
  end

  # Registration
  get "register/:token",
    to: "registrations#new",
    constraints: { token: %r{[^/]+} },
    as: "register"

  post "register/:token",
    to: "registrations#create",
    constraints: { token: %r{[^/]+} }

  resources :project_types
  resources :key_topics
  resources :categories

  resources :experts
  root "home#overview"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "home/overview", to: "home#overview", as: "home_overview"
  # Routes for login, logout, and sessions management
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"

  get "sessions/destroy"
  delete "logout", to: "sessions#destroy"

  # Additional routes
  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Calendar routes
  get "calendar/month", to: "calendar#month"
end

app/app/models/project_type.rb
# Copyright (C) 2025 Frank Mayer, Enes Korkmaz, Jascha Sonntag, Andreas Rothaler, Eray Akyazililar, Jan Magister
#
# This file is part of Elink.
#
# Elink is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Elink is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Elink. If not, see <http://www.gnu.org/licenses/>.

class ProjectType < ApplicationRecord
  validates :type_name, presence: true
  validates :type_name, format: { with: /\A(?!\s*$)[a-zA-ZäöüÄÖÜß0-9 ]{2,30}\z/ }
end

app/app/controllers/projects_controller.rb
# Copyright (C) 2025 Frank Mayer, Enes Korkmaz, Jascha Sonntag, Andreas Rothaler, Eray Akyazililar, Jan Magister
#
# This file is part of Elink.
#
# Elink is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Elink is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Elink. If not, see <http://www.gnu.org/licenses/>.

class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy remove_document
                                      add_partner remove_partner_document
                                      add_accommodation remove_accommodation_document
                                      add_catering remove_catering_document
                                      add_transport remove_transport_document
                                      delete_partner save_partner add_experts]
  before_action :authorize_user
  add_breadcrumb I18n.t("nav_bar.projects"), :projects_path

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
    @project = Project.find(params[:id])
    add_breadcrumb @project.project_name, :project_path
    @active_tab = params[:tab] || "details" # Default to 'details' if no tab is specified
  end


  # GET /projects/new
  def new
    @project = Project.new
    add_breadcrumb I18n.t("homepage.create_new_project")
  end

  # GET /projects/1/edit
  def edit
    add_breadcrumb @project.project_name, :project_path
    add_breadcrumb I18n.t("actions.edit")
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: t("notices.project_created_success") }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    @del_doc = false
    @update_params = project_params

    # Remove document removal flags from params before checking for parameter changes
    filtered_params = @update_params.except(:remove_participant_list, :remove_invitation_document, :remove_certificate_document)

    @del_doc = true if document_removal_requested?

    # Check if there are any changes in the filtered parameters (excluding document removal flags)
    if check_for_param_changes(filtered_params)
      respond_to do |format|
        if @del_doc
          if @project.update(filtered_params)
            remove_document(filtered_params)
            flash[:notices] = [ flash[:notices], t("notices.update_success") ].compact.join(" ")
            format.html { render :edit, notice: flash[:notices] }
            format.json { render :show, status: :ok, location: @project }
          else
            flash[:alerts] = [ flash[:alert], t("notices.update_failed") ].compact.join(" ")
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @project.errors, status: :unprocessable_entity }
          end
        else
          if @project.update(filtered_params)
            format.html { redirect_to @project, notice: t("notices.update_success") }
            format.json { render :show, status: :ok, location: @project }
          else
            flash[:alert] = t("notices.update_failed")
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @project.errors, status: :unprocessable_entity }
          end
        end
      end
    else
      if @del_doc
        # If only deleting doc(s)
        remove_document(filtered_params)
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy!

    respond_to do |format|
      format.html { redirect_to projects_path, status: :see_other, notice: I18n.t("notices.project_destroy") }
      format.json { head :no_content }
    end
  end

  def authorize_user
    unless current_user&.role.in?(%w[intern employee])
      flash[:alert] = I18n.t("flash.access_denied2")
      redirect_to expert_path(current_user.expert)
    end
  end

  def remove_document(filtered_params)
    %i[participant_list invitation_document certificate_document].each do |document_name|
      if params[:project]["remove_#{document_name}"] == "true"
        document = @project.send(document_name)
        if document.attached?
          document.purge_later
          message = t("notices.delete_success", document: t("activerecord.attributes.project.documents.#{document_name}"))
          # Append message if there are other changes, otherwise just show the success message
          flash[:notices] = if filtered_params.present?
                           [ flash[:notice], message ].compact.join(" ")
          else
                           message
          end
        else
            message = t("notices.delete_failed", document: t("activerecord.attributes.project.documents.#{document_name}"))
            # Append message if there are other changes, otherwise just show the failure message
            flash[:alerts] = if filtered_params.present?
                            [ flash[:alert], message ].compact.join(" ")
            else
                            message
            end
        end
      end
    end
  end

  # Add Partner Form
  def add_partner
    @partner = @project.partners.build
    render partial: "projects/form_partner", locals: { partner: @partner }
  end

  # POST or PATCH /projects/1/partners
  def save_partner
    @project = Project.find_by(id: params[:id])
    @partner_params = partner_params

    if params[:partner_id].present?
      # Find the existing partner to update
      @partner = @project.partners.find_by(id: params[:partner_id])
      if @partner.update(@partner_params)
        flash[:notice] = "Partner updated successfully!"
      else
        flash[:alert] = "Failed to update partner."
      end
    else
      # Create a new partner
      @partner = @project.partners.build(@partner_params)
      if @partner.save
        flash[:notice] = "Partner added successfully!"
      else
        flash[:alert] = "Failed to add partner."
        logger.debug "Errors: #{@partner.errors.full_messages}" # Log any validation errors
      end
    end

    respond_to do |format|
      if @partner.errors.empty?
        format.json do
          render json: {
            status: "success",
            redirect_url: project_path(@project, tab: "partners") # Redirect URL after save
          }
        end
      else
        # Determine which form to re-render based on the presence of partner_id
        form_partial = params[:partner_id].present? ? "projects/edit_partner_form" : "projects/form_partner"

        format.js do
          render partial: form_partial,
                 status: :unprocessable_entity,
                 locals: { partner: @partner }
        end

        format.json { render json: @partner.errors, status: :unprocessable_entity }
      end
    end
  end


  def edit_partner
    @project = Project.find(params[:id])
    @partner = @project.partners.find(params[:partner_id])
    render partial: "edit_partner_form", locals: { partner: @partner }
  end

  def delete_partner
    @project = Project.find(params[:id])
    @partner = @project.partners.find(params[:partner_id])

    if @partner.destroy
      flash[:notice] = "Partner deleted successfully!"
      render json: { status: "success", message: "Partner deleted successfully!", redirect_url: project_path(@project, tab: "partners") }, status: :ok
    else
      flash[:alert] = "Failed to delete partner."
      render json: { status: "error", message: "Failed to delete partner" }, status: :unprocessable_entity
    end
  end

  def remove_partner_document
    @project = Project.find(params[:id])
    @partner = @project.partners.find(params[:partner_id])

    document_type = params[:document_type]

    if %w[invoice_document quotation_document].include?(document_type)
      @partner.update(document_type => nil)
      flash[:notice] = t("notices.delete_success", document: t("activerecord.attributes.tab_docs.#{document_type}"))
    else
      flash[:alert] = t("notices.delete_failed", document: t("activerecord.attributes.tab_docs.#{document_type}"))
    end

    redirect_to project_path(@project, tab: "partners")
  end

  # Add Accommodation Form
  def add_accommodation
    @accommodation = @project.accommodations.build
    render partial: "projects/form_accommodation", locals: { accommodation: @accommodation }
  end

  # POST or PATCH /projects/1/accommodations
  def save_accommodation
    @project = Project.find_by(id: params[:id])
    @accommodation_params = accommodation_params

    if params[:accommodation_id].present?
      # Find the existing accommodation to update
      @accommodation = @project.accommodations.find_by(id: params[:accommodation_id])
      if @accommodation.update(@accommodation_params)
        flash[:notice] = "Accommodation updated successfully!"
      else
        flash[:alert] = "Failed to update accommodation."
      end
    else
      # Create a new accommodation
      @accommodation = @project.accommodations.build(@accommodation_params)
      if @accommodation.save
        flash[:notice] = "Accommodation added successfully!"
      else
        flash[:alert] = "Failed to add accommodation."

app/app/helpers/projects_helper.rb
# Copyright (C) 2025 Frank Mayer, Enes Korkmaz, Jascha Sonntag, Andreas Rothaler, Eray Akyazililar, Jan Magister
#
# This file is part of Elink.
#
# Elink is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Elink is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Elink. If not, see <http://www.gnu.org/licenses/>.

module ProjectsHelper
end

app/app/views/projects/_edit_accommodation_form.html.erb
<%
# Copyright (C) 2025 Frank Mayer, Enes Korkmaz, Jascha Sonntag, Andreas Rothaler, Eray Akyazililar, Jan Magister
#
# This file is part of Elink.
#
# Elink is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Elink is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Elink. If not, see <http://www.gnu.org/licenses/>.
%>

<!-- Outer Container Div -->
<div style="padding: 10px; background: #fff; border-radius: 5px; width: 100%; margin: 0 auto;">
  <%= form_with model: @accommodation, url: save_accommodation_project_path(@project, accommodation_id: @accommodation.id), method: :post, remote: true, html: { data: { remote: true } } do |form| %>
    <%= hidden_field_tag :accommodation_id, @accommodation.id %>
      <% if accommodation.errors.any? %>
        <div id="activerecord.error_explanation" class="py-2 px-3 mb-3 font-medium text-red-500 bg-red-50 rounded-lg" style="border: 1px solid #D40031;">
          <h2 class="heading-sub"><%= t("activerecord.errors.models.accommodation.header") %></h2>
        </div>
      <% end %>
      <!-- Accommodation Name (Required Field) -->
    <div class="flex-1 gap-2 my-3">
      <div class="flex items-center">
        <strong>
          <%= form.label :name, "#{t("activerecord.attributes.accommodation.name")}*", 
              style: "color: #{accommodation.errors[:name].any? ? '#D40031' : 'inherit'};" %>
        </strong>
      </div>  
      <%= form.text_field :name,
        style: "border: 1px solid #{accommodation.errors[:name].present? ? '#D40031' : '#D1D5DB'}; border-radius: 0.375rem; padding: 0.5rem; outline: none;", 
        class: "w-full" %>
      
      <div style="color: #D40031; font-size: 0.875rem; margin-top: 0.25rem;">
        <% if accommodation.errors[:name].any? %>
          <%= accommodation.errors[:name].first %>
        <% end %>
      </div>
    </div>
    <!-- Accommodation Status (Required Field) -->
    <div class="flex-1 gap-2 my-3">
      <div class="flex items-center">
        <strong>
          <%= form.label :status, "#{t("activerecord.attributes.accommodation.status")}*", 
              style: "color: #{accommodation.errors[:status].any? ? '#D40031' : 'inherit'};" %>
        </strong>
      </div>
      <%= form.select :status, 
        options_for_select([
          ["in Bearbeitung", "in Bearbeitung"], 
          ["angefragt", "angefragt"], 
          ["gebucht", "gebucht"]], 
          "in Bearbeitung"),
          { include_blank: t("inputfield_placeholder.choice_box_select_mandatory") }, 
        style: "border: 1px solid #{accommodation.errors[:status].present? ? '#D40031' : '#D1D5DB'}; border-radius: 0.375rem; padding: 0.5rem; outline: none;", 
          class: "w-full sm:w-[50%]" %>

      <div style="color: #D40031; font-size: 0.875rem; margin-top: 0.25rem;">
        <% if accommodation.errors[:status].any? %>
          <%= accommodation.errors[:status].first %>
        <% end %>
      </div>
    </div>
    <!-- Accommodation Address -->
    <div class="flex-1 gap-2 my-3">
      <div class="flex items-center">
        <strong>
          <%= form.label :address, t("activerecord.attributes.accommodation.address"), 
              style: "color: #{accommodation.errors[:address].any? ? '#D40031' : 'inherit'};" %>
        </strong>
      </div>  
      <%= form.text_field :address,
        style: "border: 1px solid #{accommodation.errors[:address].present? ? '#D40031' : '#D1D5DB'}; border-radius: 0.375rem; padding: 0.5rem; outline: none;", 
        class: "w-full" %>
    </div>
    <!-- Accommodation Contact -->
    <div class="flex-1 gap-2 my-3">
      <div class="flex items-center">
        <strong>
          <%= form.label :contact, t("activerecord.attributes.accommodation.contact"), 
              style: "color: #{accommodation.errors[:contact].any? ? '#D40031' : 'inherit'};" %>
        </strong>
      </div>  
      <%= form.text_field :contact,
        style: "border: 1px solid #{accommodation.errors[:contact].present? ? '#D40031' : '#D1D5DB'}; border-radius: 0.375rem; padding: 0.5rem; outline: none;", 
        class: "w-full" %>
    </div>
    <!-- Accommodation Booking Deadline -->
    <div class="flex-1 gap-2 my-3">
      <div class="flex items-center">
        <strong>
          <%= form.label :booking_deadline, t("activerecord.attributes.accommodation.booking_deadline"), 
              style: "color: #{accommodation.errors[:booking_deadline].any? ? '#D40031' : 'inherit'};" %>
        </strong>
      </div>  
      <%= form.date_field :booking_deadline,
        style: "border: 1px solid #{accommodation.errors[:booking_deadline].present? ? '#D40031' : '#D1D5DB'}; border-radius: 0.375rem; padding: 0.5rem; outline: none;", 
        class: "w-full" %>
    </div>
    <!-- Accommodation Notes -->
    <div class="flex-1 gap-2 my-3">
      <div class="flex items-center">
        <strong>
          <%= form.label :notes, t("activerecord.attributes.accommodation.notes"), 
              style: "color: #{accommodation.errors[:notes].any? ? '#D40031' : 'inherit'};" %>
        </strong>
      </div>  
      <% max_length = 500 %>
      <%= form.text_area :notes, 
        style: "border: 1px solid #{accommodation.errors[:notes].present? ? '#D40031' : '#D1D5DB'}; border-radius: 0.375rem; padding: 0.5rem; width: 100%; outline: none; min-height: 5rem;",
        maxlength: max_length,
        rows: 1, 
        oninput: "this.style.height = ''; this.style.height = this.scrollHeight + 'px';" %>
      <div class="flex gap-2 items-center">
        <!-- Display Character Count -->
        <div style="font-size: 0.875rem; margin-top: 0.25rem;">
          <% current_length = form.object.notes.present? ? form.object.notes.length : 0 %>
          <% if current_length == 0 %>
            <%= "max. #{max_length}" %>
          <% else %>
            <%= "#{current_length} / " "#{max_length}" %>
          <% end %>
        </div>
        <div style="color: #D40031; font-size: 0.875rem; margin-top: 0.25rem;">
          <% if accommodation.errors[:notes].any? %>
            <%= accommodation.errors[:notes].first %>
          <% end %>
        </div>
      </div>
    </div>
    <!-- Quotation Document Section -->
    <div class="my-5">
      <div><strong><%= "#{t("activerecord.attributes.tab_docs.quotation_document")}:" %></strong></div>
      <div class="flex gap-8 items-center">
        <% if accommodation.quotation_document.attached? %>
          <%= link_to "#{truncate(File.basename(accommodation.quotation_document.filename.to_s, File.extname(accommodation.quotation_document.filename.to_s)), length: 14, omission: '...')}#{File.extname(accommodation.quotation_document.filename.to_s)}",
                    rails_blob_path(accommodation.quotation_document, disposition: "attachment", cache_buster: Time.now.to_i),
                    title: accommodation.quotation_document.filename.to_s %>
          <!-- View document button -->
          <%= link_to rails_blob_path(accommodation.quotation_document, disposition: "inline"),
                      target: "_blank", rel: "noopener noreferrer", class: "btn flex items-center justify-between w-auto",
                      data: { cache_buster: Time.now.to_i }, title: t("actions.view") do %>
            <%= image_tag("svg/open-eye.svg") %>
            <span class="hidden ml-2 sm:inline"><%= t("actions.view") %></span>
          <% end %>
          <!-- Download document button -->
          <%= link_to rails_blob_path(accommodation.quotation_document, disposition: "attachment"),
                      class: "btn flex items-center justify-between w-auto",
                      data: { cache_buster: Time.now.to_i }, title: t("actions.download") do %>
            <%= image_tag("svg/doc-download.svg") %>
            <span class="hidden ml-2 sm:inline"><%= t("actions.download") %></span>
          <% end %>
          <!-- Delete document button -->
          <button type="button" class="flex justify-between items-center w-auto btn"
              onclick="if (confirm('<%= t('actions.confirm_delete_doc', document: accommodation.quotation_document.filename) %>')) { 
                        window.location.href = '<%= remove_accommodation_document_project_path(accommodation_id: accommodation.id, document_type: 'quotation_document') %>'; 
                      }"
              title="<%= t('actions.delete') %>">
            <%= image_tag('svg/delete.svg') %>
            <span class="hidden ml-2 sm:inline"><%= t('actions.delete') %></span>
          </button>
        <% else %>
            <span class="font-bold"><%= t("inputfield_placeholder.document_no_upload") %></span>
        <% end %>
      </div>
      <!-- Invoice  Upload -->
      <div class="flex-1 my-5">
        <!-- File Input Field -->
        <%= form.file_field :quotation_document, 
          style: "border: 1px solid #D1D5DB; border-radius: 0.375rem; padding: 0.325rem; outline: none;", 
          class: "w-full mb-2" %>
      </div>
    </div>
    <!-- Invoice Document Section -->
    <div class="my-5">
      <div><strong><%= "#{t("activerecord.attributes.tab_docs.invoice_document")}:" %></strong></div>
      <div class="flex gap-8 items-center">    
        <% if accommodation.invoice_document.attached? %>
          <%= link_to "#{truncate(File.basename(accommodation.invoice_document.filename.to_s, File.extname(accommodation.invoice_document.filename.to_s)), length: 14, omission: '...')}#{File.extname(accommodation.invoice_document.filename.to_s)}",
                    rails_blob_path(accommodation.invoice_document, disposition: "attachment", cache_buster: Time.now.to_i),
                    title: accommodation.invoice_document.filename.to_s %>
          <!-- View document button -->
          <%= link_to rails_blob_path(accommodation.invoice_document, disposition: "inline"),
                      target: "_blank", rel: "noopener noreferrer", class: "btn flex items-center justify-between w-auto",
                      data: { cache_buster: Time.now.to_i }, title: t("actions.view") do %>
            <%= image_tag("svg/open-eye.svg") %>
            <span class="hidden ml-2 sm:inline"><%= t("actions.view") %></span>
          <% end %>
          <!-- Download document button -->
          <%= link_to rails_blob_path(accommodation.invoice_document, disposition: "attachment"),
                      class: "btn flex items-center justify-between w-auto",
                      data: { cache_buster: Time.now.to_i }, title: t("actions.download") do %>
            <%= image_tag("svg/doc-download.svg") %>
            <span class="hidden ml-2 sm:inline"><%= t("actions.download") %></span>
          <% end %>
          <!-- Delete document button -->
          <button type="button" class="flex justify-between items-center w-auto btn"
                onclick="if (confirm('<%= t('actions.confirm_delete_doc', document: accommodation.invoice_document.filename) %>')) { 
                          window.location.href = '<%= remove_accommodation_document_project_path(accommodation_id: accommodation.id, document_type: 'invoice_document') %>'; 
                        }"
                title="<%= t('actions.delete') %>">
            <%= image_tag('svg/delete.svg') %>
            <span class="hidden ml-2 sm:inline"><%= t('actions.delete') %></span>
          </button>
        <% else %>
            <span class="font-bold"><%= t("inputfield_placeholder.document_no_upload") %></span>
        <% end %>
      </div>
      <!-- Invoice  Upload -->
      <div class="flex-1 my-5">
        <!-- File Input Field -->
        <%= form.file_field :invoice_document, 
          style: "border: 1px solid #D1D5DB; border-radius: 0.375rem; padding: 0.325rem; outline: none;", 
          class: "w-full mb-2" %>
      </div>
    </div>
    <!-- Save and Cancel Buttons -->
    <div class="my-3" style="display: flex; justify-content: flex-end;">
      <button type="button" class="btn cancel-btn" onclick="cancelForm('accommodation-item-<%= accommodation.id %>', 'edit')" 
              style="font-size: 12px; padding: 5px 10px; margin-right: 8px;">
        <%= t("actions.cancel") %>
      </button>
      <button type="submit" class="btn btn-save" id="accommodation-save-btn" 
              style="font-size: 12px; padding: 5px 10px;">
        <%= t("actions.save") %>
      </button>
    </div>
  <% end %>
</div>
<script>
  window.addEventListener('resize', adjustFilenames);

  document.addEventListener('DOMContentLoaded', () => {
    adjustFilenames();
  });

  function getExtension(filename) {
    return filename.slice((filename.lastIndexOf('.') - 1 >>> 0) + 2);
  }

  function getBaseFilename(filename, extension) {
      return filename.substring(0, filename.length - extension.length);
  }

  function truncateFilename(linkId, maxLength) {
      var link = document.getElementById(linkId);
      if (link) {
          var fullFilename = link.title;
          var extension = getExtension(fullFilename);
          var baseFilename = getBaseFilename(fullFilename, extension);

          var truncatedBaseFilename = baseFilename.length > maxLength ? baseFilename.substring(0, maxLength) + '...' : baseFilename;

          link.textContent = truncatedBaseFilename + extension;
      }
  }

  function adjustFilenames() {
      var maxLength = window.innerWidth < 768 ? 10 : 30;

      ['quotation_document_link', 'invoice_document_link'].forEach(linkId => {
          truncateFilename(linkId, maxLength);
      });
  }
</script>

app/app/views/projects/edit.html.erb
<%
# Copyright (C) 2025 Frank Mayer, Enes Korkmaz, Jascha Sonntag, Andreas Rothaler, Eray Akyazililar, Jan Magister
#
# This file is part of Elink.
#
# Elink is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Elink is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Elink. If not, see <http://www.gnu.org/licenses/>.
%>

<div class="container">
  <!-- Sidebar -->
  <div class="sidebar">
    <h2 class="heading"><%= t("actions.title") %></h2>
    <% if current_user.role == "employee" %>
      <%= link_to project_path, 
            class: "btn relative", 
            id: "expert_edit_cancel_editing_button", 
            onclick: "return confirm('#{I18n.t("actions.project.confirm_cancel.editing")}')" do %>
        <%= image_tag("svg/back.svg", class: "absolute left-4") %>
        <%= t("actions.back") %>
      <% end %>
      <a href="#" class="inline-block relative btn"
         onclick="document.getElementById('create_project_form').submit(); return false;">
        <%= image_tag("svg/save.svg", class: "absolute left-4") %>
        <%= t("actions.update") %>
      </a>
    <% end %>
  </div>
  <div class="flex-[3]">
    <div class="flex-[40%] w-full">
      <%= render "form_detail", project: @project %>
    </div>
  </div>
</div>